config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects
  resources :tasks
  resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, inverse_of: :project

  accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  has_many :comments
  
  accepts_nested_attributes_for :comments, reject_if: :all_blank, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @tasks = @project.tasks
  end

  # GET /projects/new
  def new
    @project = current_user.projects.new
    @task = @project.tasks.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(project_params)
    binding.pry
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, tasks_attributes: [:id, :_destroy, :status, :deadline, :title, :description])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def show
    @comments = @task.comments
    @comment = @task.comments.new
  end

  def create
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Comment was successfully added.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @comment = @task.comments.new
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:status, :deadline, :title, :description, comments_attributes: [:id, :_destroy, :description])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Project Management Tool', root_path, class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li class="active"> <%= link_to "Projects", projects_path %></li>
      <li><%= link_to 'Signout', destroy_user_session_path %> </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project Management Tool</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <h3>Project Tasks </h3>
  <div id="tasks">
    <%= form.fields_for :tasks do |task| %>
      <%= render 'task_fields', f: task %>
    <% end %>
  </div>
  <div class="links">
    <%= link_to_add_association 'Add task', form, :tasks, class: 'btn btn-sm btn-info' %>
  </div>
  <br>
  <div class="form-group">
    <%= form.submit 'Save', class: 'btn btn-sm btn-success' %>
  </div>
<% end %>

app/views/projects/_task_fields.html.erb
<div class="nested-fields panel panel-default">
  <div class="panel-body">
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class="form-check">
      <%= f.label :status, "Done", class: 'form-check-label', for: 'status_cb' %>
      <%= f.check_box :status, class: 'form-check-input', id: 'status_cb' %>
    </div>
    <div class="form-group">
      <%= f.label :deadline %>
      <%= f.text_field :deadline, class: 'form-control datepicker'%>
    </div>
    <%= link_to_remove_association "Remove", f, class: 'btn btn-sm btn-danger' %>
    </div>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.title, project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Project', new_project_path, class: 'btn btn-sm btn-info' %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <strong>Title:</strong>
  <%= @project.title %>
</h3>
<table class="table">
  <thead>
    <tr>
      <th>Tasks</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td>
          <h4><%= link_to task.title, task_path(task) %></h4>
          <br>
          <b>Description: </b><%= task.description %>
          <br>
          <b>Status:</b> <%= task.status? ? "Done" : "Not Done"%>
          <br>
          <b>Deadline:</b> <%= task.deadline %>
        </td>
      </tr>
    <% end %>
  <tbody>
</table>
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/tasks/_comment_fields.html.erb
<div class="nested-fields panel panel-default">
  <div class="panel-body">
    <div class="form-group">
      <% if f.object.description.present? %>
        <%= f.object.description%>
        <h4>Comment added on </h4> <%= f.object.created_at%>
      <% else %>
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<h3>
  <strong>Title:</strong>
  <%= @task.title %>
</h3>
<br>
<b>Description:
</b><%= @task.description %>
<br>
<b>Status:</b>
<%= @task.status? ? "Done" : "Not Done"%>
<br>
<b>Deadline:</b>
<%= @task.deadline %>
<hr>
<h4>Comments</h4>
<%= form_with(model: @task, local: true) do |form| %>
  <%= form.fields_for :comments do |comment| %>
    <%= render 'comment_fields', f: comment %>
  <% end %>
  <div class="form-group">
    <%= form.submit 'Save', class: 'btn btn-sm btn-success' %>
  </div>
<% end %>
<%= link_to 'Back', project_path(@task.project) %>